export const financedata = [
    {
        REGION: "CAR",
        "TARGET (CURRENT FUND)": 558,
        "TARGET (CONTINUING FUND)": 0,
        "TOTAL TARGET": 558,
        "ENDORSED (GRADUATES)": 358,
        "ENDORSED (STUDENTS)": 200,
        "TOTAL ENDORSED": 558,
        "ORIENTED (GRADUATES)": 450,
        "ORIENTED (STUDENTS)": 257,
        "TOTAL ORIENTED": 707,
        "DEPLOYED (GRADUATES)": 358,
        "DEPLOYED (STDENTS)": 200,
        "TOTAL DEPLOYED": 558,
        "SERVED (MALE)": 123,
        "SERVED (FEMALE)": 448,
        "SERVED M/F TOTAL": 571,
        "SERVED (GRADUATES)": 368,
        "SERVED (STUDENTS)": 203,
        "SERVED G/S TOTAL": 571,
        "OLD ()2023-2024)": 0,
        "NEW 2025": 571,
        "OLD/NEW TOTAL": 571,
        "TOTAL SERVED": 1713,
        ALLOCATION: "10,763,000.00",
        OBLIGATED: "10,763,000.00",
        "BALANCE FOR OBLIGATION": 0,
        DISBURSED: 0,
        UNDISBURSED: "10,763,000.00",
        LIQUIDATION: 0,
        UNLIQUIDATED: 0,
        "% OBLI.": "100.00%",
        "% DISB.": "0.00%",
        "% LIQUID.": "0.00%",
    },
    {
        REGION: "I",
        "TARGET (CURRENT FUND)": 900,
        "TARGET (CONTINUING FUND)": 0,
        "TOTAL TARGET": 900,
        "ENDORSED (GRADUATES)": 200,
        "ENDORSED (STUDENTS)": 100,
        "TOTAL ENDORSED": 300,
        "ORIENTED (GRADUATES)": 196,
        "ORIENTED (STUDENTS)": 95,
        "TOTAL ORIENTED": 291,
        "DEPLOYED (GRADUATES)": 0,
        "DEPLOYED (STDENTS)": 0,
        "TOTAL DEPLOYED": 0,
        "SERVED (MALE)": 0,
        "SERVED (FEMALE)": 0,
        "SERVED M/F TOTAL": 0,
        "SERVED (GRADUATES)": 0,
        "SERVED (STUDENTS)": 0,
        "SERVED G/S TOTAL": 0,
        "OLD ()2023-2024)": 0,
        "NEW 2025": 0,
        "OLD/NEW TOTAL": 0,
        "TOTAL SERVED": 0,
        ALLOCATION: "17,550,000.00",
        OBLIGATED: 0,
        "BALANCE FOR OBLIGATION": "17,550,000.00",
        DISBURSED: 0,
        UNDISBURSED: 0,
        LIQUIDATION: 0,
        UNLIQUIDATED: 0,
        "% OBLI.": "0.00%",
        "% DISB.": "0.00%",
        "% LIQUID.": "0.00%",
    },
    {
        REGION: "II",
        "TARGET (CURRENT FUND)": 600,
        "TARGET (CONTINUING FUND)": 0,
        "TOTAL TARGET": 600,
        "ENDORSED (GRADUATES)": 1000,
        "ENDORSED (STUDENTS)": 0,
        "TOTAL ENDORSED": 1000,
        "ORIENTED (GRADUATES)": 276,
        "ORIENTED (STUDENTS)": 0,
        "TOTAL ORIENTED": 276,
        "DEPLOYED (GRADUATES)": 266,
        "DEPLOYED (STDENTS)": 0,
        "TOTAL DEPLOYED": 266,
        "SERVED (MALE)": 0,
        "SERVED (FEMALE)": 0,
        "SERVED M/F TOTAL": 0,
        "SERVED (GRADUATES)": 0,
        "SERVED (STUDENTS)": 0,
        "SERVED G/S TOTAL": 0,
        "OLD ()2023-2024)": 0,
        "NEW 2025": 0,
        "OLD/NEW TOTAL": 0,
        "TOTAL SERVED": 0,
        ALLOCATION: "12,000,000.00",
        OBLIGATED: "8,400,000.00",
        "BALANCE FOR OBLIGATION": "3,600,000.00",
        DISBURSED: 0,
        UNDISBURSED: "8,400,000.00",
        LIQUIDATION: 0,
        UNLIQUIDATED: 0,
        "% OBLI.": "70.00%",
        "% DISB.": "0.00%",
        "% LIQUID.": "0.00%",
    },
] 