PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_person_profile` (
	`id` text PRIMARY KEY NOT NULL,
	`cfwp_id_no` text,
	`first_name` text,
	`middle_name` text,
	`last_name` text,
	`extension_name` integer,
	`sex_id` integer,
	`civil_status_id` integer,
	`birthdate` text,
	`age` integer,
	`birthplace` text,
	`philsys_id_no` text,
	`no_of_children` integer,
	`is_pantawid` integer DEFAULT false,
	`is_pantawid_leader` integer DEFAULT false,
	`is_slp` integer DEFAULT false,
	`sitio` text,
	`brgy_code` text,
	`is_permanent_same_as_current_address` integer DEFAULT false,
	`sitio_current_address` text,
	`barangay_code_current` text,
	`cellphone_no` text,
	`cellphone_no_secondary` text,
	`email` text,
	`has_immediate_health_concern` integer DEFAULT false,
	`immediate_health_concern` text,
	`is_lgu_official` integer DEFAULT false,
	`is_mdc` integer,
	`is_bdc` integer,
	`is_bspmc` integer,
	`is_bdrrmc_bdc_twg` integer,
	`is_bdrrmc_expanded_bdrrmc` integer,
	`is_mdrrmc` integer,
	`is_hh_head` integer,
	`academe` integer,
	`business` integer,
	`differently_abled` integer,
	`farmer` integer,
	`fisherfolks` integer,
	`government` integer,
	`school_name` text,
	`campus` text,
	`school_address` text,
	`course_id` integer,
	`year_graduated` text,
	`year_level_id` integer,
	`skills` text,
	`deployment_area_id` integer,
	`deployment_area_address` text,
	`preffered_type_of_work_id` integer,
	`representative_last_name` text,
	`representative_first_name` text,
	`representative_middle_name` text,
	`representative_extension_name_id` integer,
	`representative_sitio` text,
	`representative_brgy_code` text,
	`representative_relationship_to_beneficiary` integer,
	`representative_birthdate` text,
	`representative_age` integer,
	`representative_occupation` text,
	`representative_monthly_salary` integer,
	`representative_educational_attainment_id` integer,
	`representative_sex_id` integer,
	`representative_contact_number` text,
	`representative_id_card_id` integer,
	`representative_id_card_number` text,
	`representative_civil_status_id` integer,
	`representative_has_health_concern` integer,
	`representative_health_concern_details` text,
	`representative_skills` text,
	`ngo` integer,
	`po` integer,
	`religious` integer,
	`others` text,
	`date_of_first_appointment` text,
	`fund_source_id` integer,
	`modality_id` integer,
	`modality_sub_category_id` integer,
	`cycle_id` integer,
	`kc_mode_id` integer,
	`committee_id` integer,
	`position_id` integer,
	`volunteer_date_start` text,
	`volunteer_date_end` text,
	`training_title` text,
	`training_start` text,
	`training_end` text,
	`seminar_title` text,
	`seminar_from` text,
	`seminar_to` text,
	`seminar_hours` integer,
	`seminar_conducted_by` text,
	`date_reported` text,
	`work_name` text,
	`work_start` text,
	`work_end` text,
	`actual_cash` text,
	`actual_lcc` text,
	`is_eligible` text,
	`assessment` text,
	`current_occupation` text,
	`id_card` integer,
	`occupation_id_card_number` text,
	`family_member_name` text,
	`relationship_to_family_member` text,
	`family_member_birthday` text,
	`family_member_age` integer,
	`family_member_educational_level` text,
	`family_member_occupation` text,
	`family_member_monthly_income` integer,
	`family_member_contact_number` text,
	`type_of_cfw_id` integer,
	`year_served` integer,
	`created_date` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`created_by` text NOT NULL,
	`last_modified_date` text DEFAULT CURRENT_TIMESTAMP,
	`last_modified_by` text,
	`push_status_id` integer DEFAULT 0,
	`push_date` text DEFAULT CURRENT_TIMESTAMP,
	`deleted_date` text DEFAULT CURRENT_TIMESTAMP,
	`deleted_by` text,
	`is_deleted` integer DEFAULT false,
	`remarks` text
);
--> statement-breakpoint
INSERT INTO `__new_person_profile`("id", "cfwp_id_no", "first_name", "middle_name", "last_name", "extension_name", "sex_id", "civil_status_id", "birthdate", "age", "birthplace", "philsys_id_no", "no_of_children", "is_pantawid", "is_pantawid_leader", "is_slp", "sitio", "brgy_code", "is_permanent_same_as_current_address", "sitio_current_address", "barangay_code_current", "cellphone_no", "cellphone_no_secondary", "email", "has_immediate_health_concern", "immediate_health_concern", "is_lgu_official", "is_mdc", "is_bdc", "is_bspmc", "is_bdrrmc_bdc_twg", "is_bdrrmc_expanded_bdrrmc", "is_mdrrmc", "is_hh_head", "academe", "business", "differently_abled", "farmer", "fisherfolks", "government", "school_name", "campus", "school_address", "course_id", "year_graduated", "year_level_id", "skills", "deployment_area_id", "deployment_area_address", "preffered_type_of_work_id", "representative_last_name", "representative_first_name", "representative_middle_name", "representative_extension_name_id", "representative_sitio", "representative_brgy_code", "representative_relationship_to_beneficiary", "representative_birthdate", "representative_age", "representative_occupation", "representative_monthly_salary", "representative_educational_attainment_id", "representative_sex_id", "representative_contact_number", "representative_id_card_id", "representative_id_card_number", "representative_civil_status_id", "representative_has_health_concern", "representative_health_concern_details", "representative_skills", "ngo", "po", "religious", "others", "date_of_first_appointment", "fund_source_id", "modality_id", "modality_sub_category_id", "cycle_id", "kc_mode_id", "committee_id", "position_id", "volunteer_date_start", "volunteer_date_end", "training_title", "training_start", "training_end", "seminar_title", "seminar_from", "seminar_to", "seminar_hours", "seminar_conducted_by", "date_reported", "work_name", "work_start", "work_end", "actual_cash", "actual_lcc", "is_eligible", "assessment", "current_occupation", "id_card", "occupation_id_card_number", "family_member_name", "relationship_to_family_member", "family_member_birthday", "family_member_age", "family_member_educational_level", "family_member_occupation", "family_member_monthly_income", "family_member_contact_number", "type_of_cfw_id", "year_served", "created_date", "created_by", "last_modified_date", "last_modified_by", "push_status_id", "push_date", "deleted_date", "deleted_by", "is_deleted", "remarks") SELECT "id", "cfwp_id_no", "first_name", "middle_name", "last_name", "extension_name", "sex_id", "civil_status_id", "birthdate", "age", "birthplace", "philsys_id_no", "no_of_children", "is_pantawid", "is_pantawid_leader", "is_slp", "sitio", "brgy_code", "is_permanent_same_as_current_address", "sitio_current_address", "barangay_code_current", "cellphone_no", "cellphone_no_secondary", "email", "has_immediate_health_concern", "immediate_health_concern", "is_lgu_official", "is_mdc", "is_bdc", "is_bspmc", "is_bdrrmc_bdc_twg", "is_bdrrmc_expanded_bdrrmc", "is_mdrrmc", "is_hh_head", "academe", "business", "differently_abled", "farmer", "fisherfolks", "government", "school_name", "campus", "school_address", "course_id", "year_graduated", "year_level_id", "skills", "deployment_area_id", "deployment_area_address", "preffered_type_of_work_id", "representative_last_name", "representative_first_name", "representative_middle_name", "representative_extension_name_id", "representative_sitio", "representative_brgy_code", "representative_relationship_to_beneficiary", "representative_birthdate", "representative_age", "representative_occupation", "representative_monthly_salary", "representative_educational_attainment_id", "representative_sex_id", "representative_contact_number", "representative_id_card_id", "representative_id_card_number", "representative_civil_status_id", "representative_has_health_concern", "representative_health_concern_details", "representative_skills", "ngo", "po", "religious", "others", "date_of_first_appointment", "fund_source_id", "modality_id", "modality_sub_category_id", "cycle_id", "kc_mode_id", "committee_id", "position_id", "volunteer_date_start", "volunteer_date_end", "training_title", "training_start", "training_end", "seminar_title", "seminar_from", "seminar_to", "seminar_hours", "seminar_conducted_by", "date_reported", "work_name", "work_start", "work_end", "actual_cash", "actual_lcc", "is_eligible", "assessment", "current_occupation", "id_card", "occupation_id_card_number", "family_member_name", "relationship_to_family_member", "family_member_birthday", "family_member_age", "family_member_educational_level", "family_member_occupation", "family_member_monthly_income", "family_member_contact_number", "type_of_cfw_id", "year_served", "created_date", "created_by", "last_modified_date", "last_modified_by", "push_status_id", "push_date", "deleted_date", "deleted_by", "is_deleted", "remarks" FROM `person_profile`;--> statement-breakpoint
DROP TABLE `person_profile`;--> statement-breakpoint
ALTER TABLE `__new_person_profile` RENAME TO `person_profile`;--> statement-breakpoint
PRAGMA foreign_keys=ON;