  export interface IAllocation{
    id: string,
    date_allocation: string | null,
    region_code: string,
    pap_id: number,
    budget_year_id: number,
    appropriation_source_id: number,
    appropriation_type_id: number,
    record_status_id: number,
    allotment_manual_id: string | null,
    allotment_purpose: string | null,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
    user_id: string | null,
  }

  export interface IAllocationUacs{
    id: string,
    allocation_id: string,
    allotment_class_id: number,
    component_id: number,
    expense_id: number,
    allocation_amount: number,
    allotment_amount: number,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
    user_id: string | null,
  }

  export interface IMonthlyObligationPlan{
    id: string,
    allocation_uacs_id: string,
    amt_jan: number,
    amt_feb: number,
    amt_mar: number,
    amt_apr: number,
    amt_may: number,
    amt_jun: number,
    amt_jul: number,
    amt_aug: number,
    amt_sep: number,
    amt_oct: number,
    amt_nov: number,
    amt_dec: number,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
    user_id: string | null,
  }