export interface IPositionItem {
    id: string,
    item_code: string,
    position_id: number,
    salary_grade_id: number,
    employment_status_id: number,
    modality_id: number,
    date_abolished: string | null,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
  }

  export interface IPositionItemDistribution{
    id: string,
    position_item_id: string,
    level_id: number,
    region_code: string,
    province_code: string,
    city_code: string,
    office_id: number,
    division_id: number,
    parenthetical_title:string,
    date_distributed: string | null,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
  }

  export interface IHiringProcedure{
    id: string,
    hiring_procedure_id: number,
    position_item_distribution_id: string,
    date_target_from: string | null,
    date_target_to: string | null,
    date_actual_from: string | null,
    date_actual_to: string | null,
    reason_for_variance: string | null,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
  }

  export interface IApplicant{
    id: string,
    position_item_id: string | null,
    position_item_distribution_id: string |null,
    first_name: string,
    middle_name: string | null,
    last_name: string,
    extension_name_id: number | null,
    display_picture: Blob | null;
    sex_id: number,
    civil_status_id: number,
    birthdate: string | null,
    age: number | null,
    philsys_id_no: string |null,
    birthplace: string | null,
    status_id: number | null,
    overall_rating: number | null,
    created_date: string,
    created_by: string,
    last_modified_date: string | null,
    last_modified_by: string | null,
    push_status_id: number,
    push_date: string | null,
    deleted_date: string | null,
    deleted_by: string | null,
    is_deleted: boolean,
    remarks: string | null,
  }